<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.LocalStorage" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.0" />
    <PackageReference Include="Radzen.Blazor" Version="8.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppProject.Exceptions\AppProject.Exceptions.csproj" />
    <ProjectReference Include="..\AppProject.Resources\AppProject.Resources.csproj" />
    <ProjectReference Include="..\AppProject.Utils\AppProject.Utils.csproj" />
    <ProjectReference Include="..\AppProject.Web.ApiClient\AppProject.Web.ApiClient.csproj" />
    <ProjectReference Include="..\AppProject.Web.Models\AppProject.Web.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\" />
    <Folder Include="Pages\" />
  </ItemGroup>

</Project>
