<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AppProject.Utils\AppProject.Utils.csproj" />
    <ProjectReference Include="..\AppProject.Web.Models\AppProject.Web.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Refit" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="General\" />
  </ItemGroup>
</Project>
